services:
  db:
    image: postgres:latest
    container_name: web_list_db
    ports:
      - '5432:5432'
    volumes:
      - db_postgres:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  db_postgres: